class = "QEvent"

elements = {
    --------------------------------------------------------------------------------------------------------------------------------------------------
    {
        enum   = "Type",
        values = {
            { "None",                             cmt = "Not an event." },
            { "ActionAdded",                      cmt = "A new action has been added (QActionEvent)." },
            { "ActionChanged",                    cmt = "An action has been changed (QActionEvent)." },
            { "ActionRemoved",                    cmt = "An action has been removed (QActionEvent)." },
            { "ActivationChange",                 cmt = "A widget's top-level window activation state has changed." },
            { "ApplicationActivate",              cmt = "This enum has been deprecated. Use ApplicationStateChange instead." },
            { "ApplicationActivated",             cmt = "ApplicationActivate This enum has been deprecated. Use ApplicationStateChange instead." },
            { "ApplicationDeactivate",            cmt = "This enum has been deprecated. Use ApplicationStateChange instead." },
            { "ApplicationFontChange",            cmt = "The default application font has changed." },
            { "ApplicationLayoutDirectionChange", cmt = "The default application layout direction has changed." },
            { "ApplicationPaletteChange",         cmt = "The default application palette has changed." },
            { "ApplicationStateChange",           cmt = "The state of the application has changed." },
            { "ApplicationWindowIconChange",      cmt = "The application's icon has changed." },
            { "ChildAdded",                       cmt = "An object gets a child (QChildEvent)." },
            { "ChildPolished",                    cmt = "A widget child gets polished (QChildEvent)." },
            { "ChildRemoved",                     cmt = "An object loses a child (QChildEvent)." },
            { "ChildWindowAdded",                 cmt = "(since Qt 6.7) A child window was added to the window." },
            { "ChildWindowRemoved",               cmt = "(since Qt 6.7) A child window was removed from the window." },
            { "Clipboard",                        cmt = "The clipboard contents have changed." },
            { "Close",                            cmt = "Widget was closed (QCloseEvent)." },
            { "CloseSoftwareInputPanel",          cmt = "A widget wants to close the software input panel (SIP)." },
            { "ContentsRectChange",               cmt = "The margins of the widget's content rect changed." },
            { "ContextMenu",                      cmt = "Context popup menu (QContextMenuEvent)." },
            { "CursorChange",                     cmt = "The widget's cursor has changed." },
            { "DeferredDelete",                   cmt = "The object will be deleted after it has cleaned up (QDeferredDeleteEvent)" },
            { "DevicePixelRatioChange",           cmt = "(since Qt 6.6) The devicePixelRatio has changed for this widget's or window's underlying backing store." },
            { "DragEnter",                        cmt = "The cursor enters a widget during a drag and drop operation (QDragEnterEvent)." },
            { "DragLeave",                        cmt = "The cursor leaves a widget during a drag and drop operation (QDragLeaveEvent)." },
            { "DragMove",                         cmt = "A drag and drop operation is in progress (QDragMoveEvent)." },
            { "Drop",                             cmt = "A drag and drop operation is completed (QDropEvent)." },
            { "DynamicPropertyChange",            cmt = "A dynamic property was added, changed, or removed from the object." },
            { "EnabledChange",                    cmt = "Widget's enabled state has changed." },
            { "Enter",                            cmt = "Mouse enters widget's boundaries (QEnterEvent)." },
            { "EnterWhatsThisMode",               cmt = "Send to toplevel widgets when the application enters \"What's This?\" mode." },
            { "Expose",                           cmt = "Sent to a window when its on-screen contents are invalidated and need to be flushed from the backing store." },
            { "FileOpen",                         cmt = "File open request (QFileOpenEvent)." },
            { "FocusIn",                          cmt = "Widget or Window gains keyboard focus (QFocusEvent)." },
            { "FocusOut",                         cmt = "Widget or Window loses keyboard focus (QFocusEvent)." },
            { "FocusAboutToChange",               cmt = "Widget or Window focus is about to change (QFocusEvent)" },
            { "FontChange",                       cmt = "Widget's font has changed." },
            { "Gesture",                          cmt = "A gesture was triggered (QGestureEvent)." },
            { "GestureOverride",                  cmt = "A gesture override was triggered (QGestureEvent)." },
            { "GrabKeyboard",                     cmt = "Item gains keyboard grab (QGraphicsItem only)." },
            { "GrabMouse",                        cmt = "Item gains mouse grab (QGraphicsItem only)." },
            { "GraphicsSceneContextMenu",         cmt = "Context popup menu over a graphics scene (QGraphicsSceneContextMenuEvent)." },
            { "GraphicsSceneDragEnter",           cmt = "The cursor enters a graphics scene during a drag and drop operation (QGraphicsSceneDragDropEvent)." },
            { "GraphicsSceneDragLeave",           cmt = "The cursor leaves a graphics scene during a drag and drop operation (QGraphicsSceneDragDropEvent)." },
            { "GraphicsSceneDragMove",            cmt = "A drag and drop operation is in progress over a scene (QGraphicsSceneDragDropEvent)." },
            { "GraphicsSceneDrop",                cmt = "A drag and drop operation is completed over a scene (QGraphicsSceneDragDropEvent)." },
            { "GraphicsSceneHelp",                cmt = "The user requests help for a graphics scene (QHelpEvent)." },
            { "GraphicsSceneHoverEnter",          cmt = "The mouse cursor enters a hover item in a graphics scene (QGraphicsSceneHoverEvent)." },
            { "GraphicsSceneHoverLeave",          cmt = "The mouse cursor leaves a hover item in a graphics scene (QGraphicsSceneHoverEvent)." },
            { "GraphicsSceneHoverMove",           cmt = "The mouse cursor moves inside a hover item in a graphics scene (QGraphicsSceneHoverEvent)." },
            { "GraphicsSceneMouseDoubleClick",    cmt = "Mouse press again (double click) in a graphics scene (QGraphicsSceneMouseEvent)." },
            { "GraphicsSceneMouseMove",           cmt = "Move mouse in a graphics scene (QGraphicsSceneMouseEvent)." },
            { "GraphicsSceneMousePress",          cmt = "Mouse press in a graphics scene (QGraphicsSceneMouseEvent)." },
            { "GraphicsSceneMouseRelease",        cmt = "Mouse release in a graphics scene (QGraphicsSceneMouseEvent)." },
            { "GraphicsSceneMove",                cmt = "Widget was moved (QGraphicsSceneMoveEvent)." },
            { "GraphicsSceneResize",              cmt = "Widget was resized (QGraphicsSceneResizeEvent)." },
            { "GraphicsSceneWheel",               cmt = "Mouse wheel rolled in a graphics scene (QGraphicsSceneWheelEvent)." },
            { "GraphicsSceneLeave",               cmt = "The cursor leaves a graphics scene (QGraphicsSceneWheelEvent)." },
            { "Hide",                             cmt = "Widget was hidden (QHideEvent)." },
            { "HideToParent",                     cmt = "A child widget has been hidden." },
            { "HoverEnter",                       cmt = "The mouse cursor enters a hover widget (QHoverEvent)." },
            { "HoverLeave",                       cmt = "The mouse cursor leaves a hover widget (QHoverEvent)." },
            { "HoverMove",                        cmt = "The mouse cursor moves inside a hover widget (QHoverEvent)." },
            { "IconDrag",                         cmt = "The main icon of a window has been dragged away (QIconDragEvent)." },
            { "IconTextChange",                   cmt = "Widget's icon text has been changed. (Deprecated)" },
            { "InputMethod",                      cmt = "An input method is being used (QInputMethodEvent)." },
            { "InputMethodQuery",                 cmt = "A input method query event (QInputMethodQueryEvent)" },
            { "KeyboardLayoutChange",             cmt = "The keyboard layout has changed." },
            { "KeyPress",                         cmt = "Key press (QKeyEvent)." },
            { "KeyRelease",                       cmt = "Key release (QKeyEvent)." },
            { "LanguageChange",                   cmt = "The application translation changed." },
            { "LayoutDirectionChange",            cmt = "The direction of layouts changed." },
            { "LayoutRequest",                    cmt = "Widget layout needs to be redone." },
            { "Leave",                            cmt = "Mouse leaves widget's boundaries." },
            { "LeaveWhatsThisMode",               cmt = "Send to toplevel widgets when the application leaves \"What's This?\" mode." },
            { "LocaleChange",                     cmt = "The system locale has changed." },
            { "NonClientAreaMouseButtonDblClick", cmt = "A mouse double click occurred outside the client area (QMouseEvent)." },
            { "NonClientAreaMouseButtonPress",    cmt = "A mouse button press occurred outside the client area (QMouseEvent)." },
            { "NonClientAreaMouseButtonRelease",  cmt = "A mouse button release occurred outside the client area (QMouseEvent)." },
            { "NonClientAreaMouseMove",           cmt = "A mouse move occurred outside the client area (QMouseEvent)." },
            { "MacSizeChange",                    cmt = "The user changed his widget sizes (macOS only)." },
            { "MetaCall",                         cmt = "An asynchronous method invocation via QMetaObject::invokeMethod()." },
            { "ModifiedChange",                   cmt = "Widgets modification state has been changed." },
            { "MouseButtonDblClick",              cmt = "Mouse press again (QMouseEvent)." },
            { "MouseButtonPress",                 cmt = "Mouse press (QMouseEvent)." },
            { "MouseButtonRelease",               cmt = "Mouse release (QMouseEvent)." },
            { "MouseMove",                        cmt = "Mouse move (QMouseEvent)." },
            { "MouseTrackingChange",              cmt = "The mouse tracking state has changed." },
            { "Move",                             cmt = "Widget's position changed (QMoveEvent)." },
            { "NativeGesture",                    cmt = "The system has detected a gesture (QNativeGestureEvent)." },
            { "OrientationChange",                cmt = "The screens orientation has changes (QScreenOrientationChangeEvent)." },
            { "Paint",                            cmt = "Screen update necessary (QPaintEvent)." },
            { "PaletteChange",                    cmt = "Palette of the widget changed." },
            { "ParentAboutToChange",              cmt = "The object parent is about to change. Only sent to some object types, such as QWidget." },
            { "ParentChange",                     cmt = "The object parent has changed. Only sent to some object types, such as QWidget." },
            { "ParentWindowAboutToChange",        cmt = "(since Qt 6.7) The parent window is about to change." },
            { "ParentWindowChange",               cmt = "(since Qt 6.7) The parent window has changed." },
            { "PlatformPanel",                    cmt = "A platform specific panel has been requested." },
            { "PlatformSurface",                  cmt = "A native platform surface has been created or is about to be destroyed (QPlatformSurfaceEvent)." },
            { "Polish",                           cmt = "The widget is polished." },
            { "PolishRequest",                    cmt = "The widget should be polished." },
            { "QueryWhatsThis",                   cmt = "The widget should accept the event if it has \"What's This?\" help (QHelpEvent)." },
            { "Quit",                             cmt = "The application has exited." },
            { "ReadOnlyChange",                   cmt = " (since Qt 5.4) Widget's read-only state has changed." },
            { "RequestSoftwareInputPanel",        cmt = "A widget wants to open a software input panel (SIP)." },
            { "Resize",                           cmt = "Widget's size changed (QResizeEvent)." },
            { "ScrollPrepare",                    cmt = "The object needs to fill in its geometry information (QScrollPrepareEvent)." },
            { "Scroll",                           cmt = "The object needs to scroll to the supplied position (QScrollEvent)." },
            { "Shortcut",                         cmt = "Key press in child for shortcut key handling (QShortcutEvent)." },
            { "ShortcutOverride",                 cmt = "Key press in child, for overriding shortcut key handling (QKeyEvent). When a shortcut is about to trigger, ShortcutOverride is sent to the active window. This allows clients (e.g. widgets) to signal that they will handle the shortcut themselves, by accepting the event. If the shortcut override is accepted, the event is delivered as a normal key press to the focus widget. Otherwise, it triggers the shortcut action, if one exists." },
            { "Show",                             cmt = "Widget was shown on screen (QShowEvent)." },
            { "ShowToParent",                     cmt = "A child widget has been shown." },
            { "SockAct",                          cmt = "Socket activated, used to implement QSocketNotifier." },
            { "StateMachineSignal",               cmt = "A signal delivered to a state machine (QStateMachine::SignalEvent)." },
            { "StateMachineWrapped",              cmt = "The event is a wrapper for, i.e., contains, another event (QStateMachine::WrappedEvent)." },
            { "StatusTip",                        cmt = "A status tip is requested (QStatusTipEvent)." },
            { "StyleChange",                      cmt = "Widget's style has been changed." },
            { "TabletMove",                       cmt = "Wacom tablet move (QTabletEvent)." },
            { "TabletPress",                      cmt = "Wacom tablet press (QTabletEvent)." },
            { "TabletRelease",                    cmt = "Wacom tablet release (QTabletEvent)." },
            { "TabletEnterProximity",             cmt = "Wacom tablet enter proximity event (QTabletEvent), sent to QApplication." },
            { "TabletLeaveProximity",             cmt = "Wacom tablet leave proximity event (QTabletEvent), sent to QApplication." },
            { "TabletTrackingChange",             cmt = "(since Qt 5.9) The Wacom tablet tracking state has changed." },
            { "ThreadChange",                     cmt = "The object is moved to another thread. This is the last event sent to this object in the previous thread. See QObject::moveToThread()." },
            { "Timer",                            cmt = "Regular timer events (QTimerEvent)." },
            { "ToolBarChange",                    cmt = "The toolbar button is toggled on macOS." },
            { "ToolTip",                          cmt = "A tooltip was requested (QHelpEvent)." },
            { "ToolTipChange",                    cmt = "The widget's tooltip has changed." },
            { "TouchBegin",                       cmt = "Beginning of a sequence of touch-screen or track-pad events (QTouchEvent)." },
            { "TouchCancel",                      cmt = "Cancellation of touch-event sequence (QTouchEvent)." },
            { "TouchEnd",                         cmt = "End of touch-event sequence (QTouchEvent)." },
            { "TouchUpdate",                      cmt = "Touch-screen event (QTouchEvent)." },
            { "UngrabKeyboard",                   cmt = "Item loses keyboard grab (QGraphicsItem only)." },
            { "UngrabMouse",                      cmt = "Item loses mouse grab (QGraphicsItem, QQuickItem)." },
            { "UpdateLater",                      cmt = "The widget should be queued to be repainted at a later time." },
            { "UpdateRequest",                    cmt = "The widget should be repainted." },
            { "WhatsThis",                        cmt = "The widget should reveal \"What's This?\" help (QHelpEvent)." },
            { "WhatsThisClicked",                 cmt = "A link in a widget's \"What's This?\" help was clicked." },
            { "Wheel",                            cmt = "Mouse wheel rolled (QWheelEvent)." },
            { "WinEventAct",                      cmt = "A Windows-specific activation event has occurred." },
            { "WindowActivate",                   cmt = "Window was activated." },
            { "WindowBlocked",                    cmt = "The window is blocked by a modal dialog." },
            { "WindowDeactivate",                 cmt = "Window was deactivated." },
            { "WindowIconChange",                 cmt = "The window's icon has changed." },
            { "WindowStateChange",                cmt = "The window's state (minimized, maximized or full-screen) has changed (QWindowStateChangeEvent)." },
            { "WindowTitleChange",                cmt = "The window title has changed." },
            { "WindowUnblocked",                  cmt = "The window is unblocked after a modal dialog exited." },
            { "WinIdChange",                      cmt = "The window system identifier for this native widget has changed." },
            { "ZOrderChange",                     cmt = "The widget's z-order has changed. This event is never sent to top level windows." },
            { "SafeAreaMarginsChange",            cmt = "(since Qt 6.9) The window's safe area margins have changed." },
        }
    },
    {
        method    = "accept",
        binding   = {
            { "void", {} },
        }
    },
    {
        method    = "ignore",
        binding   = {
            { "void", {} },
        }
    },
    {
        method    = "isAccepted",
        binding   = {
            { "bool", {} },
        }
    },
    {
        method    = "setAccepted",
        binding   = {
            { "void", { "bool" } },
        }
    },
    {
        method    = "type",
        binding   = {
            { "QEvent::Type", {} },
        }
    },
    --------------------------------------------------------------------------------------------------------------------------------------------------
}

