class = "QGradient"

polymorphic = false

elements = {
    --------------------------------------------------------------------------------------------------------------------------------------------------
    {
        enum   = "CoordinateMode",
        values = {
            { "LogicalMode",         cmt = "This is the default mode. The gradient coordinates are specified logical space just like the object coordinates." },
            { "ObjectMode",          cmt = "In this mode the gradient coordinates are relative to the bounding rectangle of the object being drawn, with (0,0) in the top left corner, and (1,1) in the bottom right corner of the object's bounding rectangle. This value was added in Qt 5.12." },
            { "StretchToDeviceMode", cmt = "In this mode the gradient coordinates are relative to the bounding rectangle of the paint device, with (0,0) in the top left corner, and (1,1) in the bottom right corner of the paint device." },
            { "ObjectBoundingMode",  cmt = "This mode is the same as ObjectMode, except that the {QBrush::transform()} {brush transform}, if any, is applied relative to the logical space instead of the object space. This enum value is deprecated and should not be used in new code." },
        }
    },
    {
        enum   = "Preset",
        values = {
            "WarmFlame",
            "NightFade",
            "SpringWarmth",
            "JuicyPeach",
            "YoungPassion",
            "LadyLips",
            "SunnyMorning",
            "RainyAshville",
            "FrozenDreams",
            "WinterNeva",
            "DustyGrass",
            "TemptingAzure",
            "HeavyRain",
            "AmyCrisp",
            "MeanFruit",
            "DeepBlue",
            "RipeMalinka",
            "CloudyKnoxville",
            "MalibuBeach",
            "NewLife",
            "TrueSunset",
            "MorpheusDen",
            "RareWind",
            "NearMoon",
            "WildApple",
            "SaintPetersburg",
            "PlumPlate",
            "EverlastingSky",
            "HappyFisher",
            "Blessing",
            "SharpeyeEagle",
            "LadogaBottom",
            "LemonGate",
            "ItmeoBranding",
            "ZeusMiracle",
            "OldHat",
            "StarWine",
            "HappyAcid",
            "AwesomePine",
            "NewYork",
            "ShyRainbow",
            "MixedHopes",
            "FlyHigh",
            "StrongBliss",
            "FreshMilk",
            "SnowAgain",
            "FebruaryInk",
            "KindSteel",
            "SoftGrass",
            "GrownEarly",
            "SharpBlues",
            "ShadyWater",
            "DirtyBeauty",
            "GreatWhale",
            "TeenNotebook",
            "PoliteRumors",
            "SweetPeriod",
            "WideMatrix",
            "SoftCherish",
            "RedSalvation",
            "BurningSpring",
            "NightParty",
            "SkyGlider",
            "HeavenPeach",
            "PurpleDivision",
            "AquaSplash",
            "SpikyNaga",
            "LoveKiss",
            "CleanMirror",
            "PremiumDark",
            "ColdEvening",
            "CochitiLake",
            "SummerGames",
            "PassionateBed",
            "MountainRock",
            "DesertHump",
            "JungleDay",
            "PhoenixStart",
            "OctoberSilence",
            "FarawayRiver",
            "AlchemistLab",
            "OverSun",
            "PremiumWhite",
            "MarsParty",
            "EternalConstance",
            "JapanBlush",
            "SmilingRain",
            "CloudyApple",
            "BigMango",
            "HealthyWater",
            "AmourAmour",
            "RiskyConcrete",
            "StrongStick",
            "ViciousStance",
            "PaloAlto",
            "HappyMemories",
            "MidnightBloom",
            "Crystalline",
            "PartyBliss",
            "ConfidentCloud",
            "LeCocktail",
            "RiverCity",
            "FrozenBerry",
            "ChildCare",
            "FlyingLemon",
            "NewRetrowave",
            "HiddenJaguar",
            "AboveTheSky",
            "Nega",
            "DenseWater",
            "Seashore",
            "MarbleWall",
            "CheerfulCaramel",
            "NightSky",
            "MagicLake",
            "YoungGrass",
            "ColorfulPeach",
            "GentleCare",
            "PlumBath",
            "HappyUnicorn",
            "AfricanField",
            "SolidStone",
            "OrangeJuice",
            "GlassWater",
            "NorthMiracle",
            "FruitBlend",
            "MillenniumPine",
            "HighFlight",
            "MoleHall",
            "SpaceShift",
            "ForestInei",
            "RoyalGarden",
            "RichMetal",
            "JuicyCake",
            "SmartIndigo",
            "SandStrike",
            "NorseBeauty",
            "AquaGuidance",
            "SunVeggie",
            "SeaLord",
            "BlackSea",
            "GrassShampoo",
            "LandingAircraft",
            "WitchDance",
            "SleeplessNight",
            "AngelCare",
            "CrystalRiver",
            "SoftLipstick",
            "SaltMountain",
            "PerfectWhite",
            "FreshOasis",
            "StrictNovember",
            "MorningSalad",
            "DeepRelief",
            "SeaStrike",
            "NightCall",
            "SupremeSky",
            "LightBlue",
            "MindCrawl",
            "LilyMeadow",
            "SugarLollipop",
            "SweetDessert",
            "MagicRay",
            "TeenParty",
            "FrozenHeat",
            "GagarinView",
            "FabledSunset",
            "PerfectBlue",
        }
    },
    {
        enum   = "Spread",
        values = {
            { "PadSpread",     cmt = "The area is filled with the closest stop color. This is the default." },
            { "RepeatSpread",  cmt = "The gradient is repeated outside the gradient area." },
            { "ReflectSpread", cmt = "The gradient is reflected outside the gradient area." },
        }
    },
    {
        enum   = "Type",
        values = {
            { "LinearGradient",  cmt = "Interpolates colors between start and end points (QLinearGradient)." },
            { "RadialGradient",  cmt = "Interpolate colors between a focal point and end points on a circle surrounding it (QRadialGradient)." },
            { "ConicalGradient", cmt = "Interpolate colors around a center point (QConicalGradient)." },
            { "NoGradient",      cmt = "No gradient is used." },
        }
    },
    --------------------------------------------------------------------------------------------------------------------------------------------------
    {
        func      = "new",
        binding   = {
            { "QGradient*", { "QGradient::Preset" } },
        }
    },
    --------------------------------------------------------------------------------------------------------------------------------------------------
    {
        method    = "coordinateMode",
        binding   = {
            { "QGradient::CoordinateMode", {} },
        }
    },
    {
        method    = "setColorAt",
        binding   = {
            { "void", { "qreal", "QColor" } },
        }
    },
    {
        method    = "setCoordinateMode",
        binding   = {
            { "void", { "QGradient::CoordinateMode" } },
        }
    },
    {
        method    = "setSpread",
        binding   = {
            { "void", { "QGradient::Spread" } },
        }
    },
    {
        method    = "spread",
        binding   = {
            { "QGradient::Spread", {} },
        }
    },
    {
        method    = "type",
        binding   = {
            { "QGradient::Type", {} },
        }
    },
    --------------------------------------------------------------------------------------------------------------------------------------------------
}

