class = "QKeySequence"

elements = {
    --------------------------------------------------------------------------------------------------------------------------------------------------
    {
        enum   = "SequenceFormat",
        values = {
            "NativeText",
            "PortableText",
        }
    },
    {
        enum   = "StandardKey",
        values = {
            { "AddTab",                   cmt = "Add new tab." },
            { "Back",                     cmt = "Navigate back." },
            { "Backspace",                cmt = "Delete previous character." },
            { "Bold",                     cmt = "Bold text." },
            { "Close",                    cmt = "Close document/tab." },
            { "Copy",                     cmt = "Copy." },
            { "Cut",                      cmt = "Cut." },
            { "Delete",                   cmt = "Delete." },
            { "DeleteEndOfLine",          cmt = "Delete end of line." },
            { "DeleteEndOfWord",          cmt = "Delete word from the end of the cursor." },
            { "DeleteStartOfWord",        cmt = "Delete the beginning of a word up to the cursor." },
            { "DeleteCompleteLine",       cmt = "Delete the entire line." },
            { "Find",                     cmt = "Find in document." },
            { "FindNext",                 cmt = "Find next result." },
            { "FindPrevious",             cmt = "Find previous result." },
            { "Forward",                  cmt = "Navigate forward." },
            { "HelpContents",             cmt = "Open help contents." },
            { "InsertLineSeparator",      cmt = "Insert a new line." },
            { "InsertParagraphSeparator", cmt = "Insert a new paragraph." },
            { "Italic",                   cmt = "Italic text." },
            { "MoveToEndOfBlock",         cmt = "Move cursor to end of block. This shortcut is only used on Apple platforms." },
            { "MoveToEndOfDocument",      cmt = "Move cursor to end of document." },
            { "MoveToEndOfLine",          cmt = "Move cursor to end of line." },
            { "MoveToNextChar",           cmt = "Move cursor to next character." },
            { "MoveToNextLine",           cmt = "Move cursor to next line." },
            { "MoveToNextPage",           cmt = "Move cursor to next page." },
            { "MoveToNextWord",           cmt = "Move cursor to next word." },
            { "MoveToPreviousChar",       cmt = "Move cursor to previous character." },
            { "MoveToPreviousLine",       cmt = "Move cursor to previous line." },
            { "MoveToPreviousPage",       cmt = "Move cursor to previous page." },
            { "MoveToPreviousWord",       cmt = "Move cursor to previous word." },
            { "MoveToStartOfBlock",       cmt = "Move cursor to start of a block. This shortcut is only used on Apple platforms." },
            { "MoveToStartOfDocument",    cmt = "Move cursor to start of document." },
            { "MoveToStartOfLine",        cmt = "Move cursor to start of line." },
            { "New",                      cmt = "Create new document." },
            { "NextChild",                cmt = "Navigate to next tab or child window." },
            { "Open",                     cmt = "Open document." },
            { "Paste",                    cmt = "Paste." },
            { "Preferences",              cmt = "Open the preferences dialog." },
            { "PreviousChild",            cmt = "Navigate to previous tab or child window." },
            { "Print",                    cmt = "Print document." },
            { "Quit",                     cmt = "Quit the application." },
            { "Redo",                     cmt = "Redo." },
            { "Refresh",                  cmt = "Refresh or reload current document." },
            { "Replace",                  cmt = "Find and replace." },
            { "SaveAs",                   cmt = "Save document after prompting the user for a file name." },
            { "Save",                     cmt = "Save document." },
            { "SelectAll",                cmt = "Select all text." },
            { "Deselect",                 cmt = "Deselect text. Since 5.1" },
            { "SelectEndOfBlock",         cmt = "Extend selection to the end of a text block. This shortcut is only used on Apple platforms." },
            { "SelectEndOfDocument",      cmt = "Extend selection to end of document." },
            { "SelectEndOfLine",          cmt = "Extend selection to end of line." },
            { "SelectNextChar",           cmt = "Extend selection to next character." },
            { "SelectNextLine",           cmt = "Extend selection to next line." },
            { "SelectNextPage",           cmt = "Extend selection to next page." },
            { "SelectNextWord",           cmt = "Extend selection to next word." },
            { "SelectPreviousChar",       cmt = "Extend selection to previous character." },
            { "SelectPreviousLine",       cmt = "Extend selection to previous line." },
            { "SelectPreviousPage",       cmt = "Extend selection to previous page." },
            { "SelectPreviousWord",       cmt = "Extend selection to previous word." },
            { "SelectStartOfBlock",       cmt = "Extend selection to the start of a text block. This shortcut is only used on Apple platforms." },
            { "SelectStartOfDocument",    cmt = "Extend selection to start of document." },
            { "SelectStartOfLine",        cmt = "Extend selection to start of line." },
            { "Underline",                cmt = "Underline text." },
            { "Undo",                     cmt = "Undo." },
            { "UnknownKey",               cmt = "Unbound key." },
            { "WhatsThis",                cmt = "Activate \"what's this\"." },
            { "ZoomIn",                   cmt = "Zoom in." },
            { "ZoomOut",                  cmt = "Zoom out." },
            { "FullScreen",               cmt = "Toggle the window state to/from full screen." },
            { "Cancel",                   cmt = "Cancel the current operation." },
        }
    },
    --------------------------------------------------------------------------------------------------------------------------------------------------
    {
        func      = "new",
        binding   = {
            { "QKeySequence@", { "QKeySequence::StandardKey" } },
            { "QKeySequence@", { "QString" } },
            { "QKeySequence@", { "QString", "QKeySequence::SequenceFormat" } },
        }
    },
    --------------------------------------------------------------------------------------------------------------------------------------------------
    --------------------------------------------------------------------------------------------------------------------------------------------------
}

